theme = "vixelated"
[editor]
auto-completion = true
auto-format = true
auto-save = true
clipboard-provider = "wayland"
color-modes = true
line-number = "relative"
text-width = 80
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 1

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "file-base-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
separator = "│"

[editor.statusline.mode]
insert = "I"
normal = "N"
select = "S"

[keys.normal]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-J = ["extend_to_line_bounds", "yank", "paste_after", "move_line_down"]
A-K = ["extend_to_line_bounds", "yank", "paste_before"]
